# Generated by Django 3.1.7 on 2021-04-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fireDetect', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
